i=(input("enter the words "))
t=tuple(map(int,i.split(",")))

length=len(t)
sort=sorted(t)
summm=sum(t)
maximum=max(t)
minimum=min(t)
counted=t.count(4)
print(f"The tuple is : {t}")
print(f"The sorted tuple is :{sort}")
print(f"The sum is :{summm}")
print(f"The maximun number among them is : {maximum}")
print(f"The minimum number among them is : {minimum}")
print(f"the count of number 4 is :{counted}")