fruit = []
f1= input("Enter the 1st fruit Name  ")
fruit.append(f1)
f2= input("Enter the 2nd fruit Name  ")
fruit.append(f2)
f3= input("Enter the 3rd fruit Name  ")
fruit.append(f3)
f4= input("Enter the 4rth fruit Name  ")
fruit.append(f4)
f5= input("Enter the 5th fruit Name  ")
fruit.append(f5)
f6= input("Enter the 6th fruit Name  ")
fruit.append(f6)
f7= input("Enter the 7th fruit Name  ")
fruit.append(f7)
print(fruit)