s1=set()
s=int(input("Enter the number 1 "))
s1.add(s)
s=int(input("Enter the number 2 "))
s1.add(s)
s=int(input("Enter the number3 "))
s1.add(s)
s=int(input("Enter the number 4 "))
s1.add(s)
s =int(input("Enter the number 5 "))
s1.add(s)
s=int(input("Enter the number 6 "))
s1.add(s)
s =int(input("Enter the number7 "))
s1.add(s)
s=int(input("Enter the number 8 "))
s1.add(s)
print(s1)